Bump required glib build dependency
While meson.build indicates that 2.66 is enough, one of the tests
introduced API that is only available to 2.68 which leads to package
build failure:

../../../testsuite/reftests/gtk-reftest.c: In function ‘log_writer’:
../../../testsuite/reftests/gtk-reftest.c:537:7: warning: implicit declaration of function ‘g_log_writer_default_would_drop’; did you mean ‘g_log_writer_default’? [-Wimplicit-function-declaration]
  537 |  if (!g_log_writer_default_would_drop (log_level, NULL))
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       g_log_writer_default
../../../testsuite/reftests/gtk-reftest.c:537:7: warning: nested extern declaration of ‘g_log_writer_default_would_drop’ [-Wnested-externs]